{% set name = "tealdeer" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dbrgn/tealdeer/archive/v{{ version }}.tar.gz
  sha256: d42db25a56a72faec173c86192656c5381281dc197171f385fccffd518930430

build:
  number: 0
  skip: True  # [ppc64le]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - tldr --help

about:
  home: https://github.com/dbrgn/tealdeer
  license: Apache-2.0
  license_file:
    - LICENSE-APACHE
    - THIRDPARTY.yml
  summary: Very fast implementation of tldr in Rust
  dev_url: https://github.com/dbrgn/tealdeer

extra:
  recipe-maintainers:
    - danielnachun
