context:
  version: "1.8.0"

package:
  name: tealdeer
  version: ${{ version }}

source:
  url: https://github.com/dbrgn/tealdeer/archive/v${{ version }}.tar.gz
  sha256: b1f1262de60ef3105ff93de71568a68a56ad5874a28f105ab7cb5857d305cdb9

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - tldr --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE-APACHE
    - THIRDPARTY.yml
  summary: Very fast implementation of tldr in Rust
  homepage: https://github.com/dbrgn/tealdeer
  repository: https://github.com/dbrgn/tealdeer

extra:
  recipe-maintainers:
    - danielnachun
