context:
  version: 1.7.1

package:
  name: tealdeer
  version: ${{ version }}

source:
  url: https://github.com/dbrgn/tealdeer/archive/v${{ version }}.tar.gz
  sha256: 2b10e141774d2a50d25a1d3ca3d911dedc0e1313366ce0a364068c7a686300d8

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - tldr --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE-APACHE
    - THIRDPARTY.yml
  summary: Very fast implementation of tldr in Rust
  homepage: https://github.com/dbrgn/tealdeer
  repository: https://github.com/dbrgn/tealdeer

extra:
  recipe-maintainers:
    - danielnachun
